updates

diff --git a/.ddev/commands/web/install b/.ddev/commands/web/install
--- a/.ddev/commands/web/install
+++ b/.ddev/commands/web/install
@@ -7,17 +7,27 @@
 # Make sure the script stops on failure
 set -eu -o pipefail
 
-# Passive aggressive message.
+git config --global --add safe.directory /usr/local/quickstart-install-profile
 echo "Deleting all project files and folders..."
-
 # Remove all files and folders in the project directory within the web
 # container, and not the project directory on the host.
 rm -rf /var/www/html/*
+
 BRANCH_NAME=$(git -C /usr/local/quickstart-install-profile rev-parse --abbrev-ref HEAD); if [ $(git ls-remote --heads https://github.com/az-digital/az-quickstart-scaffolding.git $BRANCH_NAME | wc -l) = 1 ]; then SCAFFOLD_BRANCH="$BRANCH_NAME"; else SCAFFOLD_BRANCH="main"; fi; git clone --branch $SCAFFOLD_BRANCH https://github.com/az-digital/az-quickstart-scaffolding.git /var/www/html
 composer config repositories.localdev path /usr/local/quickstart-install-profile && composer require --no-update az-digital/az_quickstart:\*@dev
 BRANCH_NAME=$(git -C /usr/local/quickstart-install-profile rev-parse --abbrev-ref HEAD); if [ $(git ls-remote --heads https://github.com/az-digital/az-quickstart-dev.git $BRANCH_NAME | wc -l) = 1 ]; then DEV_PACKAGE_BRANCH="$BRANCH_NAME"; else DEV_PACKAGE_BRANCH=main; fi; composer require --no-update --dev az-digital/az-quickstart-dev:dev-${DEV_PACKAGE_BRANCH}
+
 composer install
+
 drush --root=/var/www/html/web site:install --account-mail=noreply@email.arizona.edu --account-name=azadmin --account-pass=azadmin2024 --db-url=mysql://db:db@db:3306/db -y --verbose
 drush --root=/var/www/html/web config:set -y az_cas.settings disable_login_form 0
 drush --root=/var/www/html/web cache:rebuild
+
+# Ensure yarn is installed and accessible
+if ! command -v yarn &> /dev/null
+then
+    echo "yarn could not be found, installing..."
+    npm install -g yarn
+fi
+
 yarn --cwd /usr/local/quickstart-install-profile install
