#4597: Fix more logic in prepare-for-minor-release workflow. (2.x)

diff --git a/.github/workflows/prepare-for-minor-release.yml b/.github/workflows/prepare-for-minor-release.yml
--- a/.github/workflows/prepare-for-minor-release.yml
+++ b/.github/workflows/prepare-for-minor-release.yml
@@ -17,13 +17,16 @@ jobs:
 
   validate_source_branch:
     runs-on: ubuntu-latest
-    if: ${{ !contains(fromJSON('["main", "2.x"]'), github.ref_name) }}
     steps:
       - name: Validate source branch
         run: |
-          echo "Workflow triggered from invalid branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
-          echo "Worfklow must be triggerd from a valid development branch (i.e. main or 2.x)" >> $GITHUB_STEP_SUMMARY
-          exit 1
+          dev_branches=("main" "2.x")
+          # Check if the search_string is present in the array
+          if ! [[ " ${dev_branches[@]} " =~ " ${GITHUB_REF_NAME} " ]]; then
+            echo "Workflow triggered from invalid branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
+            echo "Worfklow must be triggered from a valid development branch (i.e. main or 2.x)" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
 
   validate_release_branch:
     runs-on: ubuntu-latest
@@ -101,7 +104,7 @@ jobs:
           echo "Dev branch alias: $DEV_BRANCH_ALIAS" >> $GITHUB_STEP_SUMMARY
 
   dispatch:
-    needs: 
+    needs:
       - validate_source_branch
       - validate_release_branch
       - branch_name_prep
